language: python

python:
  - "3.5"
  - "3.6"
env:
  - PYTHON_FLAVOR=standard
  - PYTHON_FLAVOR=conda

matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true
      env:
        - PYTHON_FLAVOR=standard
    - python: "3.7"
      dist: xenial
      sudo: true
      env:
        - PYTHON_FLAVOR=conda

before_install:
  - if [[ $PYTHON_FLAVOR == "conda" ]];
    then
        export PATH=/home/travis/miniconda3/bin:$PATH &&
        bash .conda_ci_before_install.sh;
     else
        pip install --upgrade pip;
     fi

install:
  - if [[ $PYTHON_FLAVOR == "conda" ]];
    then
        bash .conda_ci_install.sh;
    else
        pip install .[test];
    fi

# Run test
script:
  - nosetests --with-coverage --cover-package=pweave

# Calculate coverage
after_success:
   - pip install python-coveralls
   - coveralls
